version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: ${DB_NAME}
    hostname: postgres # コンテナ内での名前
    restart: always
    user: ${POSTGRES_CONTAINER_USER}
